name: Test Admin Console
description: Run Test Admin Console
inputs:
  sdk-version:
    description: Javascript SDK version to use
    required: true
runs:
  using: "composite"
  steps:
    - name: Start Kuzzle stack
      run: |
        sudo sysctl -w vm.max_map_count=262144
        ./.ci/start_kuzzle.sh
        npm ci
      shell: bash
    - name: Setup Admin console
      run: |
        git clone -b 4-dev https://github.com/kuzzleio/kuzzle-admin-console /tmp/admin-console
        cd /tmp/admin-console
        npm ci
        npm install kuzzle-sdk-v${{ inputs.sdk-version }}@${{ env.GITHUB_WORKSPACE }}
      shell: bash
    - name: Run e2e tests
      run: |
        cd ${{ env.GITHUB_WORKSPACE }}/test/e2e/run-test
        npm ci
        cd ${{ env.GITHUB_WORKSPACE }}
        CYPRESS_RETRIES=5 npm run test:e2e
      shell: bash
