name: Test Admin Console
description: Run Test Admin Console
inputs:
  sdk-version:
    description: Javascript SDK version to use
    required: true
runs:
  using: "composite"
  steps:
    - name: Start Kuzzle stack
      run: |
        export GITHUB_DIR=$(pwd)
        sudo sysctl -w vm.max_map_count=262144
        npm ci
      shell: bash
    - name: Setup Admin console
      run: |
        git clone -b 4-dev https://github.com/kuzzleio/kuzzle-admin-console /tmp/admin-console
        cd /tmp/admin-console
        npm ci
        npm install kuzzle-sdk-v${{ inputs.sdk-version }}@$GITHUB_DIR
      shell: bash
    - name: Run e2e tests
      run: |
        cd /tmp/admin-console/test/e2e/run-test
        npm ci
        cd ../
        docker-compose -f stack-v2.yml up -d
        cd /tmp/admin-console
        CYPRESS_RETRIES=5 npm run test:e2e
      shell: bash
