name: Test Admin Console
description: Run Test Admin Console
inputs:
  sdk-version:
    description: Javascript SDK version to use
    required: true
  cypress-key:
    description: Cypress record key
    required: true
runs:
  using: "composite"
  steps:
    - name: Start Kuzzle stack
      run: |
        sudo sysctl -w vm.max_map_count=262144
        npm i -g npm
        npm ci
      shell: bash
    - name: Setup Admin console
      run: |
        export GITHUB_DIR=$(pwd)
        git clone -b 4-dev https://github.com/kuzzleio/kuzzle-admin-console /tmp/admin-console
        cp -f ./cypress.json /tmp/admin-console/cypress.json
        cd /tmp/admin-console
        npm ci
        npm uninstall kuzzle-sdk-v${{ inputs.sdk-version }}
        npm install kuzzle-sdk-v${{ inputs.sdk-version }}@"$GITHUB_DIR"
        cd ./node_modules/kuzzle-sdk-v${{ inputs.sdk-version }} && npm run build
      shell: bash
    - name: Run e2e tests
      run: |
        cd /tmp/admin-console/test/e2e/run-test
        npm ci
        cd /tmp/admin-console
        CYPRESS_RETRIES=5 npm run test:e2e -- --backend=2
      env:
        CYPRESS_RECORD_KEY: ${{ inputs.cypress-key }} 
      shell: bash
