import type { DocumentContent, JSONObject } from "kuzzle-types";

// Moved to kuzzle-types, the API contract shared by kuzzle and kuzzle-sdk
// (Kuzzle ADR-0002 step 03). `Document` stays here: it is a class, a runtime
// value, which the types-only kuzzle-types declares as an interface.
export type { DocumentContent, DocumentMetadata } from "kuzzle-types";

/**
 * Kuzzle document
 *
 * @deprecated Use "KDocument" interface
 */
export class Document {
  /**
   * Document unique ID
   */
  _id: string;
  /**
   * Document Version (generated by Elasticsearch)
   */
  _version?: number;
  /**
   * If true, a new document was created,
   * otherwise the document existed and was updated
   * @see https://docs.kuzzle.io/sdk/js/7/controllers/document/upsert/
   */
  created?: boolean;
  /**
   * Document Content
   */
  _source: DocumentContent;

  [key: string]: JSONObject | any;
}

/**
 * Document retrieved from a search
 *
 * @deprecated Use "KHit"
 */
export interface DocumentHit extends Document {
  /**
   * Relevance score
   */
  _score: number;
}
