name: Deploy doc
description: Run Deploy doc
runs:
  using: "composite"
  steps:
    - run: sudo apt install python python-pip -y
      shell: bash
    - run: pip install awscli --upgrade --user
      shell: bash
    - run: npm install --production=false
      shell: bash
    - run: npm run doc-prepare
      shell: bash
    - run: npm run doc-build
      shell: bash
    - run: npm run doc-upload
      shell: bash
    - run: npm run doc-cloudfront
      shell: bash
