name: Tests Docs
description: Run Tests Docs
runs:
  using: "composite"
  steps: 
    - run: npm install
      shell: bash
    - run: npm run build
      shell: bash
    - run: npm run doc-testing
      shell: bash
