name: Documentation Snippets Tests
description: Run Documentation Snippets Tests
runs:
  using: "composite"
  steps:
    - name: Build the Stack
      run: |
        npm install
        npm run build
      shell: bash
    - run: npm run doc-testing
      shell: bash
