name: Documentation Snippets Tests
description: Run Documentation Snippets Tests
inputs:
  CYPRESS_RECORD_KEY_DOC:
    description: Cypress project key
    required: true
runs:
  using: "composite"
  steps:
    - name: Build the Stack
      run: |
        npm install
        npm run build
      shell: bash
    - run: npm run doc-testing
      env:
        CYPRESS_RECORD_KEY_DOC: ${{ inputs.CYPRESS_RECORD_KEY_DOC }}
      shell: bash
