name: ESLint
description: Run ESLint
runs:
  using: "composite"
  steps:
    - name: Install deps
      run: npm i -g npm && npm install
      shell: bash
    - name: Run lint
      run: npm run test:lint
      shell: bash
