name: ESLint
description: Run ESLint
runs:
  using: "composite"
  steps:
    - name: Install deps
      run: npm install && node --version && npm -- version
      shell: bash
    - name: Run lint
      run: npm run test:lint
      shell: bash
