name: Admin Console
description: Run Admin Console Tests
runs:
  using: "composite"
  steps: 
    - run: sudo sysctl -w vm.max_map_count=262144
      shell: bash
    - run: ./.ci/start_kuzzle.sh
      shell: bash
    - run: npm ci
      shell: bash
    - run: git clone -b 4-dev https://github.com/kuzzleio/kuzzle-admin-console /tmp/admin-console
      shell: bash
    - run: cd /tmp/admin-console
      shell: bash
    - run: npm ci
      shell: bash
    - run: npm install kuzzle-sdk-v${{ inputs.kuzzle-sdk }}@npm:kuzzle-sdk@${{ inputs.kuzzle-sdk }}
      shell: bash
    - run: cd test/e2e/run-test && npm ci && cd -
      shell: bash
    - run: CYPRESS_RETRIES=5 npm run test:e2e
      shell: bash

