name: Integration Tests
description: Run Integration Tests
inputs:
  CYPRESS_RECORD_KEY_DOC:
    description: Cypress project key
    required: true
runs:
  using: "composite"
  steps:
    - name: Start Kuzzle stack
      run: |
        sudo sysctl -w vm.max_map_count=262144
        "./.ci/start_kuzzle.sh"
      shell: bash
    - name: Build Kuzzle
      run: |
        npm install
        npm run build
      shell: bash
    - name: Run functional tests
      run: npm run test:functional
      env:
        CYPRESS_RECORD_KEY_DOC: ${{ inputs.CYPRESS_RECORD_KEY_DOC }}
      shell: bash
