name: Integration Tests
description: Run Integration Tests
runs:
  using: "composite"
  steps: 
    - run: "./.ci/start_kuzzle.sh"
      shell: bash
    - run: npm install
      shell: bash
    - run: npm run build
      shell: bash
    - run: npm run test:functional
      shell: bash
