name: Dead links Tests

on: [pull_request]

jobs:
  dead-links:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Documentation tests
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: npm ci
      - run: npm run doc-prepare
      - run: $(npm bin)/kuzdoc iterate-repos:install --repos_path doc/framework/.repos/
      - run: $(npm bin)/kuzdoc framework:link -d /sdk/js/7/ -v 7
      - run: gem install typhoeus
      - run: cd doc/framework/ && HYDRA_MAX_CONCURRENCY=20 travis_retry ruby .ci/dead-links.rb -p src/sdk/js/7/
